ens_jobeet_homepage:
    pattern:  /
    defaults: { _controller: EnsJobeetBundle:Default:index }

ens_jobeet_show:
    pattern:  /job/{id}/show
    defaults: { _controller: EnsJobeetBundle:Default:show }
